# GNU Make project makefile autogenerated by Premake
ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifndef CC
  CC = gcc
endif

ifndef CXX
  CXX = g++
endif

ifndef AR
  AR = ar
endif

ifeq ($(config),debug)
  OBJDIR     = obj/Debug/codekiddy
  TARGETDIR  = ../../build
  TARGET     = $(TARGETDIR)/play.exe
  DEFINES   += -DDEBUG
  INCLUDES  += -I../../depends/box2d/include -I../../depends/luabind/include -I../../depends/clanlib/include -I../../depends/luajit/include -I../../depends/awesomium/include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -mwindows -L../../depends/box2d/build -L../../depends/luabind/build -L../../depends/clanlib/lib -L../../depends/luajit/lib -L../../depends/awesomium/lib -L../../depends/box2D/build
  LIBS      += -lbox2d -lluabind -lLua51 -lclanApp-static-mt -lclanCore-static-mt -lclanCSSLayout-static-mt -lclanDatabase-static-mt -lclanDisplay-static-mt -lclanGL1-static-mt -lclanGL-static-mt -lclanGUI-static-mt -lclanMikMod-static-mt -lclanNetwork-static-mt -lclanRegExp-static-mt -lclanSound-static-mt -lclanSqlite-static-mt -lclanSWRender-static-mt -lclanVorbis-static-mt
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += ../../depends/box2D/build/libbox2d.a ../../depends/luabind/build/libluabind.a
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release)
  OBJDIR     = obj/Release/codekiddy
  TARGETDIR  = ../../build
  TARGET     = $(TARGETDIR)/play.exe
  DEFINES   += -DNDEBUG
  INCLUDES  += -I../../depends/box2d/include -I../../depends/luabind/include -I../../depends/clanlib/include -I../../depends/luajit/include -I../../depends/awesomium/include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O2
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -s -mwindows -L../../depends/box2d/build -L../../depends/luabind/build -L../../depends/clanlib/lib -L../../depends/luajit/lib -L../../depends/awesomium/lib -L../../depends/box2D/build
  LIBS      += -lbox2d -lluabind -lLua51 -lclanApp-static-mt -lclanCore-static-mt -lclanCSSLayout-static-mt -lclanDatabase-static-mt -lclanDisplay-static-mt -lclanGL1-static-mt -lclanGL-static-mt -lclanGUI-static-mt -lclanMikMod-static-mt -lclanNetwork-static-mt -lclanRegExp-static-mt -lclanSound-static-mt -lclanSqlite-static-mt -lclanSWRender-static-mt -lclanVorbis-static-mt
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += ../../depends/box2D/build/libbox2d.a ../../depends/luabind/build/libluabind.a
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

OBJECTS := \
	$(OBJDIR)/Camera.o \
	$(OBJDIR)/CBoundingBox.o \
	$(OBJDIR)/CDisplayWindow.o \
	$(OBJDIR)/CEventHandler.o \
	$(OBJDIR)/CFontDescription.o \
	$(OBJDIR)/CFontObject.o \
	$(OBJDIR)/CFrameBuffer.o \
	$(OBJDIR)/CGraphicContext.o \
	$(OBJDIR)/CInputContext.o \
	$(OBJDIR)/CInputDevice.o \
	$(OBJDIR)/CInputEvent.o \
	$(OBJDIR)/CLight.o \
	$(OBJDIR)/CMarchingSquare.o \
	$(OBJDIR)/CMesh.o \
	$(OBJDIR)/CPhysBody.o \
	$(OBJDIR)/CPhysData.o \
	$(OBJDIR)/CPhysFilter.o \
	$(OBJDIR)/CPhysJoint.o \
	$(OBJDIR)/CPhysListener.o \
	$(OBJDIR)/CPhysRay.o \
	$(OBJDIR)/CShader.o \
	$(OBJDIR)/CSprite.o \
	$(OBJDIR)/CVertexAttribute.o \
	$(OBJDIR)/CVertexAttributes.o \
	$(OBJDIR)/CVertexBufferObject.o \
	$(OBJDIR)/Display.o \
	$(OBJDIR)/Events.o \
	$(OBJDIR)/Files.o \
	$(OBJDIR)/Fonts.o \
	$(OBJDIR)/Game.o \
	$(OBJDIR)/Inputs.o \
	$(OBJDIR)/Lights.o \
	$(OBJDIR)/Lua.o \
	$(OBJDIR)/main.o \
	$(OBJDIR)/Network.o \
	$(OBJDIR)/Physics.o \
	$(OBJDIR)/Render.o \
	$(OBJDIR)/Sounds.o \
	$(OBJDIR)/Time.o \
	$(OBJDIR)/Util.o \

RESOURCES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

.PHONY: clean prebuild prelink

all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking codekiddy
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning codekiddy
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH)
	@echo $(notdir $<)
	-$(SILENT) cp $< $(OBJDIR)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
endif

$(OBJDIR)/Camera.o: ../../source/Camera.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/CBoundingBox.o: ../../source/CBoundingBox.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/CDisplayWindow.o: ../../source/CDisplayWindow.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/CEventHandler.o: ../../source/CEventHandler.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/CFontDescription.o: ../../source/CFontDescription.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/CFontObject.o: ../../source/CFontObject.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/CFrameBuffer.o: ../../source/CFrameBuffer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/CGraphicContext.o: ../../source/CGraphicContext.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/CInputContext.o: ../../source/CInputContext.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/CInputDevice.o: ../../source/CInputDevice.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/CInputEvent.o: ../../source/CInputEvent.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/CLight.o: ../../source/CLight.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/CMarchingSquare.o: ../../source/CMarchingSquare.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/CMesh.o: ../../source/CMesh.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/CPhysBody.o: ../../source/CPhysBody.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/CPhysData.o: ../../source/CPhysData.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/CPhysFilter.o: ../../source/CPhysFilter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/CPhysJoint.o: ../../source/CPhysJoint.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/CPhysListener.o: ../../source/CPhysListener.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/CPhysRay.o: ../../source/CPhysRay.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/CShader.o: ../../source/CShader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/CSprite.o: ../../source/CSprite.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/CVertexAttribute.o: ../../source/CVertexAttribute.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/CVertexAttributes.o: ../../source/CVertexAttributes.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/CVertexBufferObject.o: ../../source/CVertexBufferObject.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Display.o: ../../source/Display.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Events.o: ../../source/Events.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Files.o: ../../source/Files.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Fonts.o: ../../source/Fonts.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Game.o: ../../source/Game.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Inputs.o: ../../source/Inputs.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Lights.o: ../../source/Lights.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Lua.o: ../../source/Lua.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/main.o: ../../source/main.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Network.o: ../../source/Network.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Physics.o: ../../source/Physics.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Render.o: ../../source/Render.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Sounds.o: ../../source/Sounds.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Time.o: ../../source/Time.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Util.o: ../../source/Util.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"

-include $(OBJECTS:%.o=%.d)
